SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[MACHINE_DATA_STR](
	[RESULT_ID] [int] NOT NULL,
	[MACHINE_COLUMNS_ID] [int] NOT NULL,
	[DATA] [varchar](255) NOT NULL,
 CONSTRAINT [PK_MACHINE_DATA_STR] PRIMARY KEY CLUSTERED 
(
	[RESULT_ID] ASC,
	[MACHINE_COLUMNS_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[MACHINE_DATA_STR]  WITH CHECK ADD  CONSTRAINT [FK_MACHINE_DATA_STR_RESULT] FOREIGN KEY([RESULT_ID])
REFERENCES [dbo].[RESULT] ([TRAN_ID])
GO

ALTER TABLE [dbo].[MACHINE_DATA_STR] CHECK CONSTRAINT [FK_MACHINE_DATA_STR_RESULT]
GO
