SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[MACHINE](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[LINE_ID] [int] NOT NULL,
	[SEQ] [int] NOT NULL,
	[MACHINE_NO] [int] NOT NULL,
	[MACHINE_NAME] [varchar](10) NOT NULL,
	[PATH] varchar(20) NOT NULL,	
	[PLC_NET] int NOT NULL,
	[PLC_NODE] int NOT NULL,
	[PLC_UNIT] int NOT NULL,
	[READ_STATUS_ADDRESS] int NOT NULL,
	[READ_STATUS_LENGTH] int NOT NULL,
	[READ_DATA_ADDRESS] int NOT NULL,
	[WRITE_STATUS_ADDRESS] int NOT NULL,
	[WRITE_LIFE_ADDRESS] int NOT NULL,
	[WRITE_SYNC_ADDRESS] int NOT NULL,
	[COPY_FILE] bit NOT NULL,
	[COPY_PATH] nvarchar(255) NOT NULL,
	[COPY_WILDCARD] varchar(50) NOT NULL,
	[COPY_PURGE_OLD_PATH] nvarchar(255) NOT NULL,
	[COPY_PERIOD_MILLISEC] int NOT NULL,
	[COPY_PURGE_PERIOD_DAY] int NOT NULL,
	[FORMAT_SERIAL] varchar(100) NOT NULL,
	[FORMAT_MODE] varchar(100) NOT NULL,
	[FORMAT_MC] varchar(100) NOT NULL,
	[FORMAT_LOT_NO] varchar(100) NOT NULL,
	[FORMAT_FILE_NAME] varchar(100) NOT NULL,
	[FORMAT_DATE_TIME] varchar(100) NOT NULL,
	[FORMAT_STATUS] varchar(100) NOT NULL,
	
 CONSTRAINT [PK_MACHINE] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[MACHINE]  WITH CHECK ADD  CONSTRAINT [FK_MACHINE_LINE_MASTER] FOREIGN KEY([LINE_ID])
REFERENCES [dbo].[LINE_MASTER] ([ID])
GO

ALTER TABLE [dbo].[MACHINE] CHECK CONSTRAINT [FK_MACHINE_LINE_MASTER]
GO

CREATE UNIQUE NONCLUSTERED INDEX [UX_MACHINE_LINE_ID_SEQ] ON [dbo].[MACHINE]
(
	[LINE_ID] ASC,
	[SEQ] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE UNIQUE NONCLUSTERED INDEX [UX_MACHINE_LINE_ID_MACHINE_NAME] ON [dbo].[MACHINE]
(
	[LINE_ID] ASC,
	[MACHINE_NAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


