BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
CREATE TABLE dbo.LINE_MASTER
	(
	ID int NOT NULL IDENTITY (1, 1),
	LINE_NAME varchar(50) NOT NULL,
	SEQ int NOT NULL,
	ROOT_PATH varchar(255) NOT NULL,
	ROOT_TEMP varchar(255) NOT NULL,
	SLEEP_INTERVAL int NOT NULL,
	READ_ASCII_LENGTH int NOT NULL,
	READ_BCD_LENGTH int NOT NULL,
	SYNC_TIME_WHEN varchar(10) NOT NULL,
	USE_CSV_MODE bit NOT NULL,
	USE_XLS_MODE bit NOT NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.LINE_MASTER ADD CONSTRAINT
	PK_LINE_MASTER PRIMARY KEY CLUSTERED 
	(
	ID
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.LINE_MASTER SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
