SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[MACHINE_COLUMNS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[MACHINE_ID] [int] NOT NULL,
	[SEQ] [int] NOT NULL,
	[SCREEN_COLUMN_NAME] [varchar](255) NOT NULL,
	[FILE_COLUMN_NAME] [varchar](255) NOT NULL,
	[DATA_TYPE] [char](1) NOT NULL,
	[POSITION] int NOT NULL,
	[LENGTH] int NOT NULL,
	[MULTIPLIER] float NULL,
	[FORMAT_STRING] varchar(50) NULL,
	[REPLACE_COLUMN_NAME] [varchar](255) NOT NULL,
	
 CONSTRAINT [PK_MACHINE_COLUMNS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[MACHINE_COLUMNS]  WITH CHECK ADD  CONSTRAINT [FK_MACHINE_COLUMNS_MACHINE] FOREIGN KEY([MACHINE_ID])
REFERENCES [dbo].[MACHINE] ([ID])
GO

ALTER TABLE [dbo].[MACHINE_COLUMNS] CHECK CONSTRAINT [FK_MACHINE_COLUMNS_MACHINE]
GO

CREATE UNIQUE NONCLUSTERED INDEX [UX_MACHINE_COLUMNS_MACHINE_ID_SEQ] ON [dbo].[MACHINE_COLUMNS]
(
	[MACHINE_ID] ASC,
	[SEQ] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
