USE [ITT-DB1-PRDDATA]

ALTER TABLE LOT_PART ADD PART_NAME varchar(100) NULL;
ALTER TABLE LOT_PART ADD PART_LOT_NO_2 varchar(100) NULL;
ALTER TABLE LOT_PART ADD QTY_2 varchar(100) NULL;
ALTER TABLE LOT_PART ADD PART_LOT_NO_3 varchar(100) NULL;
ALTER TABLE LOT_PART ADD QTY_3 varchar(100) NULL;

/*
2016-06-03 17:10:15.273		Add LOT2 LOT3 columns to LOT_PART		
*/
INSERT INTO [schema_migrations] ([VERSION],[DESCR],[SQL_SCRIPT])
VALUES
('2016-06-03 17:10:15.273'
,'Add LOT2 LOT3 columns to LOT_PART'
,'ALTER TABLE LOT_PART ADD PART_NAME varchar(100) NULL;
ALTER TABLE LOT_PART ADD PART_LOT_NO_2 varchar(100) NULL;
ALTER TABLE LOT_PART ADD QTY_2 varchar(100) NULL;
ALTER TABLE LOT_PART ADD PART_LOT_NO_3 varchar(100) NULL;
ALTER TABLE LOT_PART ADD QTY_3 varchar(100) NULL;')
GO

